### ISSUE TITLE
Some extra information

### ISSUE THREAD

**Issue by aljoflo** [OMCS/RPiSort#1]
Hi ollie this is a very interesting project, do you have some extra information or a video where we be able to see it working? thanks in advance!

**Comment by OMCS** [comment]
Hi, thanks for your interest! May I ask how you found this? Are you building something similar for a project? I uploaded this repository as an interview portfolio piece based off of work I did a few years ago. I thought it was set to private but that must have changed when my GitHub plan expired.

As I was working for a company at the time anything proprietary (such as the libraries required for this to compile) haven't been included, but it's still a grey area so this should probably be removed.

If you're doing something with the Pi for educational / non-commercial use I would be very happy to discuss with you! Feel free to email me with some more details if you're interested. o.saunders [at] gmx.com
